packages:
  - packages/**
  - playground/**

catalog:
  '@nuxt/eslint-config': latest
  '@nuxt/scripts': latest
  '@nuxt/test-utils': latest
  '@nuxt/ui': latest
  eslint: latest
  nuxt: 4.1.0
  typescript: latest
  vue: latest
  vue-router: latest
  zod: latest
  vitest: latest
  vite: latest
  '@vitest/browser-playwright': latest
  'vitest-browser-vue': latest
  playwright: latest
  '@playwright/test': latest
  'happy-dom': latest

onlyBuiltDependencies:
  - better-sqlite3
  - sqlite3
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
