export default [
  { id: 1, name: 'France', code: 'FR', emoji: '🇫🇷', region: 'Europe' },
  { id: 2, name: 'Japan', code: 'JP', emoji: '🇯🇵', region: 'Asia' },
  { id: 3, name: 'Canada', code: 'CA', emoji: '🇨🇦', region: 'North America' },
  { id: 4, name: 'Germany', code: 'DE', emoji: '🇩🇪', region: 'Europe' },
  { id: 5, name: 'Brazil', code: 'BR', emoji: '🇧🇷', region: 'South America' },
  { id: 6, name: 'Australia', code: 'AU', emoji: '🇦🇺', region: 'Oceania' },
  { id: 7, name: 'India', code: 'IN', emoji: '🇮🇳', region: 'Asia' },
  { id: 8, name: 'Italy', code: 'IT', emoji: '🇮🇹', region: 'Europe' },
  { id: 9, name: 'Mexico', code: 'MX', emoji: '🇲🇽', region: 'North America' },
  { id: 10, name: 'South Africa', code: 'ZA', emoji: '🇿🇦', region: 'Africa' },
  { id: 11, name: 'China', code: 'CN', emoji: '🇨🇳', region: 'Asia' },
  { id: 12, name: 'Russia', code: 'RU', emoji: '🇷🇺', region: 'Europe' },
  { id: 13, name: 'United Kingdom', code: 'GB', emoji: '🇬🇧', region: 'Europe' },
  { id: 14, name: 'United States', code: 'US', emoji: '🇺🇸', region: 'North America' },
  { id: 15, name: 'Spain', code: 'ES', emoji: '🇪🇸', region: 'Europe' },
  { id: 16, name: 'Argentina', code: 'AR', emoji: '🇦🇷', region: 'South America' },
  { id: 17, name: 'South Korea', code: 'KR', emoji: '🇰🇷', region: 'Asia' },
  { id: 18, name: 'Egypt', code: 'EG', emoji: '🇪🇬', region: 'Africa' },
  { id: 19, name: 'New Zealand', code: 'NZ', emoji: '🇳🇿', region: 'Oceania' },
  { id: 20, name: 'Sweden', code: 'SE', emoji: '🇸🇪', region: 'Europe' },
  { id: 21, name: 'Nigeria', code: 'NG', emoji: '🇳🇬', region: 'Africa' },
  { id: 22, name: 'Saudi Arabia', code: 'SA', emoji: '🇸🇦', region: 'Asia' },
  { id: 23, name: 'Turkey', code: 'TR', emoji: '🇹🇷', region: 'Asia' },
  { id: 24, name: 'Greece', code: 'GR', emoji: '🇬🇷', region: 'Europe' },
  { id: 25, name: 'Thailand', code: 'TH', emoji: '🇹🇭', region: 'Asia' }
]
