INSERT INTO countries (name, code, emoji, region) VALUES
('Afghanistan','AF','openmoji:flag-afghanistan',3),
('Aland Islands','AX','openmoji:flag-aland-islands',2),
('Albania','AL','openmoji:flag-albania',2),
('Algeria','DZ','openmoji:flag-algeria',4),
('American Samoa','AS','openmoji:flag-american-samoa',5),
('Andorra','AD','openmoji:flag-andorra',2),
('Angola','AO','openmoji:flag-angola',4),
('Anguilla','AI','openmoji:flag-anguilla',1),
('Antigua and Barbuda','AG','openmoji:flag-antigua-and-barbuda',1),
('Argentina','AR','openmoji:flag-argentina',1),
('Armenia','AM','openmoji:flag-armenia',3),
('Aruba','AW','openmoji:flag-aruba',1),
('Australia','AU','openmoji:flag-australia',5),
('Austria','AT','openmoji:flag-austria',2),
('Azerbaijan','AZ','openmoji:flag-azerbaijan',3),
('Bahrain','BH','openmoji:flag-bahrain',3),
('Bangladesh','BD','openmoji:flag-bangladesh',3),
('Barbados','BB','openmoji:flag-barbados',1),
('Belarus','BY','openmoji:flag-belarus',2),
('Belgium','BE','openmoji:flag-belgium',2),
('Belize','BZ','openmoji:flag-belize',1),
('Benin','BJ','openmoji:flag-benin',4),
('Bermuda','BM','openmoji:flag-bermuda',1),
('Bhutan','BT','openmoji:flag-bhutan',3),
('Bolivia','BO','openmoji:flag-bolivia',1),
('Bosnia and Herzegovina','BA','openmoji:flag-bosnia-and-herzegovina',2),
('Botswana','BW','openmoji:flag-botswana',4),
('Brazil','BR','openmoji:flag-brazil',1),
('British Indian Ocean Territory','IO','openmoji:flag-british-indian-ocean-territory',4),
('Brunei','BN','openmoji:flag-brunei',3),
('Bulgaria','BG','openmoji:flag-bulgaria',2),
('Burkina Faso','BF','openmoji:flag-burkina-faso',4),
('Burundi','BI','openmoji:flag-burundi',4),
('Cambodia','KH','openmoji:flag-cambodia',3),
('Cameroon','CM','openmoji:flag-cameroon',4),
('Canada','CA','openmoji:flag-canada',1),
('Cape Verde','CV','openmoji:flag-cape-verde',4),
('Cayman Islands','KY','openmoji:flag-cayman-islands',1),
('Central4 Republic','CF','openmoji:flag-central4-republic',4),
('Chad','TD','openmoji:flag-chad',4),
('Chile','CL','openmoji:flag-chile',1),
('China','CN','openmoji:flag-china',3),
('Christmas Island','CX','openmoji:flag-christmas-island',5),
('Colombia','CO','openmoji:flag-colombia',1),
('Comoros','KM','openmoji:flag-comoros',4),
('Cook Islands','CK','openmoji:flag-cook-islands',5),
('Costa Rica','CR','openmoji:flag-costa-rica',1),
('Cote D''Ivoire (Ivory Coast)','CI','openmoji:flag-cote-divoire',4),
('Croatia','HR','openmoji:flag-croatia',2),
('Cuba','CU','openmoji:flag-cuba',1),
('Cyprus','CY','openmoji:flag-cyprus',2),
('Czech Republic','CZ','openmoji:flag-czechia',2),
('Denmark','DK','openmoji:flag-denmark',2),
('Djibouti','DJ','openmoji:flag-djibouti',4),
('Dominica','DM','openmoji:flag-dominica',1),
('Dominican Republic','DO','openmoji:flag-dominican-republic',1),
('Ecuador','EC','openmoji:flag-ecuador',1),
('Egypt','EG','openmoji:flag-egypt',4),
('El Salvador','SV','openmoji:flag-el-salvador',1),
('Equatorial Guinea','GQ','openmoji:flag-equatorial-guinea',4),
('Eritrea','ER','openmoji:flag-eritrea',4),
('Estonia','EE','openmoji:flag-estonia',2),
('Eswatini','SZ','openmoji:flag-eswatini',4),
('Ethiopia','ET','openmoji:flag-ethiopia',4),
('Falkland Islands','FK','openmoji:flag-falkland-islands',1),
('Faroe Islands','FO','openmoji:flag-faroe-islands',2),
('Fiji Islands','FJ','openmoji:flag-fiji',5),
('Finland','FI','openmoji:flag-finland',2),
('France','FR','openmoji:flag-france',2),
('French Guiana','GF','openmoji:flag-french-guiana',1),
('French Polynesia','PF','openmoji:flag-french-polynesia',5),
('French Southern Territories','TF','openmoji:flag-french-southern-territories',4),
('Gabon','GA','openmoji:flag-gabon',4),
('Georgia','GE','openmoji:flag-georgia',3),
('Germany','DE','openmoji:flag-germany',2),
('Ghana','GH','openmoji:flag-ghana',4),
('Gibraltar','GI','openmoji:flag-gibraltar',2),
('Greece','GR','openmoji:flag-greece',2),
('Greenland','GL','openmoji:flag-greenland',1),
('Grenada','GD','openmoji:flag-grenada',1),
('Guadeloupe','GP','openmoji:flag-guadeloupe',1),
('Guam','GU','openmoji:flag-guam',5),
('Guatemala','GT','openmoji:flag-guatemala',1),
('Guernsey','GG','openmoji:flag-guernsey',2),
('Guinea','GN','openmoji:flag-guinea',4),
('Guinea-Bissau','GW','openmoji:flag-guinea-bissau',4),
('Guyana','GY','openmoji:flag-guyana',1),
('Haiti','HT','openmoji:flag-haiti',1),
('Honduras','HN','openmoji:flag-honduras',1),
('Hong Kong S.A.R.','HK','openmoji:flag-hong-kong-sar-china',3),
('Hungary','HU','openmoji:flag-hungary',2),
('Iceland','IS','openmoji:flag-iceland',2),
('India','IN','openmoji:flag-india',3),
('Indonesia','ID','openmoji:flag-indonesia',3),
('Iran','IR','openmoji:flag-iran',3),
('Iraq','IQ','openmoji:flag-iraq',3),
('Ireland','IE','openmoji:flag-ireland',2),
('Israel','IL','openmoji:flag-israel',3),
('Italy','IT','openmoji:flag-italy',2),
('Jamaica','JM','openmoji:flag-jamaica',1),
('Japan','JP','openmoji:flag-japan',3),
('Jersey','JE','openmoji:flag-jersey',2),
('Jordan','JO','openmoji:flag-jordan',3),
('Kazakhstan','KZ','openmoji:flag-kazakhstan',3),
('Kenya','KE','openmoji:flag-kenya',4),
('Kiribati','KI','openmoji:flag-kiribati',5),
('Kosovo','XK','openmoji:flag-kosovo',2),
('Kuwait','KW','openmoji:flag-kuwait',3),
('Kyrgyzstan','KG','openmoji:flag-kyrgyzstan',3),
('Laos','LA','openmoji:flag-laos',3),
('Latvia','LV','openmoji:flag-latvia',2),
('Lebanon','LB','openmoji:flag-lebanon',3),
('Lesotho','LS','openmoji:flag-lesotho',4),
('Liberia','LR','openmoji:flag-liberia',4),
('Libya','LY','openmoji:flag-libya',4),
('Liechtenstein','LI','openmoji:flag-liechtenstein',2),
('Lithuania','LT','openmoji:flag-lithuania',2),
('Luxembourg','LU','openmoji:flag-luxembourg',2),
('Madagascar','MG','openmoji:flag-madagascar',4),
('Malawi','MW','openmoji:flag-malawi',4),
('Malaysia','MY','openmoji:flag-malaysia',3),
('Maldives','MV','openmoji:flag-maldives',3),
('Mali','ML','openmoji:flag-mali',4),
('Malta','MT','openmoji:flag-malta',2),
('Marshall Islands','MH','openmoji:flag-marshall-islands',5),
('Martinique','MQ','openmoji:flag-martinique',1),
('Mauritania','MR','openmoji:flag-mauritania',4),
('Mauritius','MU','openmoji:flag-mauritius',4),
('Mayotte','YT','openmoji:flag-mayotte',4),
('Mexico','MX','openmoji:flag-mexico',1),
('Micronesia','FM','openmoji:flag-micronesia',5),
('Moldova','MD','openmoji:flag-moldova',2),
('Monaco','MC','openmoji:flag-monaco',2),
('Mongolia','MN','openmoji:flag-mongolia',3),
('Montenegro','ME','openmoji:flag-montenegro',2),
('Montserrat','MS','openmoji:flag-montserrat',1),
('Morocco','MA','openmoji:flag-morocco',4),
('Mozambique','MZ','openmoji:flag-mozambique',4),
('Namibia','NA','openmoji:flag-namibia',4),
('Nauru','NR','openmoji:flag-nauru',5),
('Nepal','NP','openmoji:flag-nepal',3),
('Netherlands','NL','openmoji:flag-netherlands',2),
('New Caledonia','NC','openmoji:flag-new-caledonia',5),
('New Zealand','NZ','openmoji:flag-new-zealand',5),
('Nicaragua','NI','openmoji:flag-nicaragua',1),
('Niger','NE','openmoji:flag-niger',4),
('Nigeria','NG','openmoji:flag-nigeria',4),
('Niue','NU','openmoji:flag-niue',5),
('Norfolk Island','NF','openmoji:flag-norfolk-island',5),
('North Korea','KP','openmoji:flag-north-korea',3),
('North Macedonia','MK','openmoji:flag-north-macedonia',2),
('Northern Mariana Islands','MP','openmoji:flag-northern-mariana-islands',5),
('Norway','NO','openmoji:flag-norway',2),
('Oman','OM','openmoji:flag-oman',3),
('Pakistan','PK','openmoji:flag-pakistan',3),
('Palau','PW','openmoji:flag-palau',5),
('Palestinian','PS','openmoji:flag-palestinian-territories',3),
('Panama','PA','openmoji:flag-panama',1),
('Papua New Guinea','PG','openmoji:flag-papua-new-guinea',5),
('Paraguay','PY','openmoji:flag-paraguay',1),
('Peru','PE','openmoji:flag-peru',1),
('Philippines','PH','openmoji:flag-philippines',3),
('Poland','PL','openmoji:flag-poland',2),
('Portugal','PT','openmoji:flag-portugal',2),
('Puerto Rico','PR','openmoji:flag-puerto-rico',1),
('Qatar','QA','openmoji:flag-qatar',3),
('Reunion','RE','openmoji:flag-reunion',4),
('Romania','RO','openmoji:flag-romania',2),
('Russia','RU','openmoji:flag-russia',2),
('Rwanda','RW','openmoji:flag-rwanda',4),
('Samoa','WS','openmoji:flag-samoa',5),
('San Marino','SM','openmoji:flag-san-marino',2),
('Sao Tome and Principe','ST','openmoji:flag-sao-tome-and-principe',4),
('Saudi Arabia','SA','openmoji:flag-saudi-arabia',3),
('Senegal','SN','openmoji:flag-senegal',4),
('Serbia','RS','openmoji:flag-serbia',2),
('Seychelles','SC','openmoji:flag-seychelles',4),
('Sierra Leone','SL','openmoji:flag-sierra-leone',4),
('Singapore','SG','openmoji:flag-singapore',3),
('Sint Maarten (Dutch part)','SX','openmoji:flag-sint-maarten',1),
('Slovakia','SK','openmoji:flag-slovakia',2),
('Slovenia','SI','openmoji:flag-slovenia',2),
('Solomon Islands','SB','openmoji:flag-solomon-islands',5),
('Somalia','SO','openmoji:flag-somalia',4),
('South Korea','KR','openmoji:flag-south-korea',3),
('Spain','ES','openmoji:flag-spain',2),
('Sudan','SD','openmoji:flag-sudan',4),
('Suriname','SR','openmoji:flag-suriname',1),
('Sweden','SE','openmoji:flag-sweden',2),
('Switzerland','CH','openmoji:flag-switzerland',2),
('Syria','SY','openmoji:flag-syria',3),
('Taiwan','TW','openmoji:flag-taiwan',3),
('Tajikistan','TJ','openmoji:flag-tajikistan',3),
('Tanzania','TZ','openmoji:flag-tanzania',4),
('Thailand','TH','openmoji:flag-thailand',3),
('Timor-Leste','TL','openmoji:flag-timor-leste',3),
('Togo','TG','openmoji:flag-togo',4),
('Tokelau','TK','openmoji:flag-tokelau',5),
('Tonga','TO','openmoji:flag-tonga',5),
('Tunisia','TN','openmoji:flag-tunisia',4),
('Turkey','TR','openmoji:flag-turkiye',3),
('Turkmenistan','TM','openmoji:flag-turkmenistan',3),
('Tuvalu','TV','openmoji:flag-tuvalu',5),
('Uganda','UG','openmoji:flag-uganda',4),
('Ukraine','UA','openmoji:flag-ukraine',2),
('United Arab Emirates','AE','openmoji:flag-united-arab-emirates',3),
('United Kingdom','GB','openmoji:flag-united-kingdom',2),
('United States','US','openmoji:flag-united-states',1),
('Uruguay','UY','openmoji:flag-uruguay',1),
('Uzbekistan','UZ','openmoji:flag-uzbekistan',3),
('Vanuatu','VU','openmoji:flag-vanuatu',5),
('Venezuela','VE','openmoji:flag-venezuela',1),
('Vietnam','VN','openmoji:flag-vietnam',3),
('Yemen','YE','openmoji:flag-yemen',3),
('Zambia','ZM','openmoji:flag-zambia',4),
('Zimbabwe','ZW','openmoji:flag-zimbabwe',4);