name: CI

on:
   pull_request:
      branches:
         -  main
         -  dev

jobs:
   lint:
      name: Linting
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout code
            uses: actions/checkout@v2

         -  uses: pnpm/action-setup@v4
            name: Install pnpm
            with:
               run_install: false

         -  name: Install Node.js
            uses: actions/setup-node@v4
            with:
               node-version: 20
               cache: pnpm

         -  name: Install dependencies
            run: pnpm install

         -  name: Run linting
            run: pnpm lint

   tests:
      name: Run tests
      runs-on: ubuntu-latest
      needs: lint
      steps:

         -  name: Checkout code
            uses: actions/checkout@v2

         -  uses: pnpm/action-setup@v4
            name: Install pnpm
            with:
               run_install: false

         -  name: Install Node.js
            uses: actions/setup-node@v4
            with:
               node-version: 20
               cache: pnpm
         -  name: Install Playwright Browsers
            run: npx playwright install chromium --with-deps

         -  name: Install dependencies
            run: pnpm install

         -  name: Run e2e tests
            run: pnpm test
